### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by qqaadir** [lewjiayi/Vehicle-Headlight-Tracker#4]
Could you please help with this error?

Traceback (most recent call last):

  File "C:\Users\user\Downloads\Vehicle-Headlight-Tracker-master\Vehicle-Headlight-Tracker-master\detct.py", line 85, in <module>
    contours, hierarchy = cv2.findContours(t, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

ValueError: too many values to unpack (expected 2)

**Comment by qqaadir** [comment]
Worked with this change.

  _, contours, hierarchy = cv2.findContours(t, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

**Comment by lewjiayi** [comment]
It could be the difference of OpenCV version. The latest version will return 3 values instead of 2, which the first being an processed image. You can read more on here https://stackoverflow.com/questions/25504964/opencv-python-valueerror-too-many-values-to-unpack

**Comment by qqaadir** [comment]
@lewjiayi  Thank you very much. I was going to ask, could you please add some documentation on how to use your code.  A demo on how to operate after running this code,  screenshots of a test video and its output would very help. Also, I want to understand your technique, is there a paper I can refer to please ?
